name: iDDS-atlas
dependencies:
- python==3.6
- pip
- pip:
  - futures                          # multiple process/threads
  - unittest2        # unit test tool
  - pep8             # checks for PEP8 code style compliance
  - flake8           # Wrapper around PyFlakes&pep8
  - pytest           # python testing tool
  - nose             # nose test tools
  - stomp.py
  - panda-client-light     # panda client
  - rucio-clients
  - rucio-clients-atlas
  - idds-common==2.0.9
  - idds-workflow==2.0.9