name: idds-client
dependencies:
- python==3.6
- pip
- pip:
  - requests                         # requests
  - urllib3                          # url connections
  - flask                            # web service
  - futures                          # multiple process/threads
  - stomp.py                         # Messaging broker client
  - unittest2        # unit test tool
  - pep8             # checks for PEP8 code style compliance
  - flake8           # Wrapper around PyFlakes&pep8
  - pytest           # python testing tool
  - nose             # nose test tools
  - tabulate
  - idds-common==0.5.1
  - idds-workflow==0.5.1