name: iDDS
dependencies:
- python==3.6
- pip
- pip:
  - unittest2        # unit test tool
  - pep8             # checks for PEP8 code style compliance
  - flake8           # Wrapper around PyFlakes&pep8
  - pytest           # python testing tool
  - nose             # nose test tools
  - idds-common==0.5.2